basePath: /
definitions:
  controller.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  controller.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  controller.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  controller.TokenResponse:
    properties:
      token:
        type: string
    type: object
  model.Student:
    type: object
  model.User:
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: 基于 MySQL、Gin 和 JWT 的学生管理系统 API 文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 学生管理系统 API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口，返回 JWT Token
      parameters:
      - description: 登录信息
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/controller.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功，返回 Token
          schema:
            $ref: '#/definitions/controller.TokenResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: 认证失败
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: 用户登录
      tags:
      - 认证
  /auth/register:
    post:
      consumes:
      - application/json
      description: 新用户注册接口
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: 注册成功
          schema:
            $ref: '#/definitions/controller.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: 用户注册
      tags:
      - 认证
  /students:
    get:
      description: 获取所有学生的信息列表
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            items:
              $ref: '#/definitions/model.Student'
            type: array
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      security:
      - BearerAuth: []
      summary: 获取学生信息列表
      tags:
      - 学生管理
    post:
      consumes:
      - application/json
      description: 创建新的学生信息
      parameters:
      - description: 学生信息
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/model.Student'
      produces:
      - application/json
      responses:
        "201":
          description: 创建成功
          schema:
            $ref: '#/definitions/controller.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      security:
      - BearerAuth: []
      summary: 创建学生信息
      tags:
      - 学生管理
  /students/{id}:
    delete:
      description: 根据学生 ID 删除学生的信息
      parameters:
      - description: 学生 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/controller.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      security:
      - BearerAuth: []
      summary: 删除学生信息
      tags:
      - 学生管理
    get:
      description: 根据学生 ID 获取单个学生的信息
      parameters:
      - description: 学生 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/model.Student'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: 学生信息不存在
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      security:
      - BearerAuth: []
      summary: 获取单个学生信息
      tags:
      - 学生管理
    put:
      consumes:
      - application/json
      description: 根据学生 ID 更新学生的信息
      parameters:
      - description: 学生 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新后的学生信息
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/model.Student'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            $ref: '#/definitions/controller.SuccessResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: 学生信息不存在
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      security:
      - BearerAuth: []
      summary: 更新学生信息
      tags:
      - 学生管理
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
